### ISSUE TITLE
[Feature request] - Enumerate all cached keys

### ISSUE THREAD

**Issue by RanaInside** [bitfaster/BitFaster.Caching#110]
Use Case: basically I am caching some db records with an external functions that deletes the records using different properties and not the key. Work around for now is to read the key from database before deleting them, and then use the key to remove from cache.

Having an option to enumerate all keys would give me to do a faster way of checking those properties in memory instead of database: and that would be sweet.

Additionally it also be used for diagnostic purposes.

**Comment by bitfaster** [comment]
It sounds like you need something like secondary indexes based on the additional properties, mapping each property to the cache primary key (which you would then use to delete).

In any case, this is the second request I had to enumerate all keys so I will add it.
