### ISSUE TITLE
FastConcurrentTLru's Constructor timetolive is not precise on liunx mac platform

### ISSUE THREAD

**Issue by 442575816** [bitfaster/BitFaster.Caching#117]
`FastConcurrentTLru` use `TLruLongTicksPolicy`. this policy discard item by

```C#
[MethodImpl(MethodImplOptions.AggressiveInlining)]
public bool ShouldDiscard(LongTickCountLruItem<K, V> item)
{
    if (Stopwatch.GetTimestamp() - item.TickCount > this.timeToLive)
    {
        return true;
    }

    return false;
}
```

but the Stopwatch.GetTimestamp() has platform different result. see

https://stackoverflow.com/questions/67205283/stopwatch-gettimestamp-produced-different-results-on-linux-vs-windows

**Comment by 442575816** [comment]
on macos platform the scale is 1000x

**Comment by bitfaster** [comment]
Thanks for reporting this, I'll take a look.

**Comment by 442575816** [comment]
thanks

**Comment by bitfaster** [comment]
I don't have a Mac to repro this, please could you run the program below and give the results:

```
class Program
{
    static void Main()
    {
        Console.WriteLine(Stopwatch.Frequency);
        Console.WriteLine(TimeSpan.TicksPerSecond);

        Console.WriteLine(Stopwatch.GetTimestamp());
        Thread.Sleep(TimeSpan.FromSeconds(1));
        Console.WriteLine(Stopwatch.GetTimestamp());
    }
}
```

I will then use to sanity check my fix. Thanks!

**Comment by 442575816** [comment]
the result is:
```
1000000000
10000000
10000000
1026619477472300
1026620481623899
```

**Comment by 442575816** [comment]
this my macbook pro info:
<img width="545" alt="image" src="https://user-images.githubusercontent.com/44646849/164858263-e1987244-ae2b-4c7a-9a27-3948ab2000d2.png">

**Comment by bitfaster** [comment]
Thanks for the info - a fix is now checked in.
