### ISSUE TITLE
NuGet package is missing intellisense xml file

### ISSUE THREAD

**Issue by bording** [bitfaster/BitFaster.Caching#229]
I noticed that I wasn't getting any intellisense documentation while using the package even though you've got documentation comments in the code.

I took a quick look at the project file, and the reason the xml documentation file isn't being included in the package is that `<GenerateDocumentationFile>true</GenerateDocumentationFile>` is missing from the `PropertyGroup`.

It would be very helpful to have that added!

**Comment by bitfaster** [comment]
Thanks for letting me know - I'll fix this in the next release.
