### ISSUE TITLE
[Feature request] individual items expiry

### ISSUE THREAD

**Issue by alex-jitbit** [bitfaster/BitFaster.Caching#269]
Item-specific expiry TTL.

Probably by inheriting `LruItem` and `LruItemPolicy` implementation that will implement individual expiry for items.

**Comment by bitfaster** [comment]
There is some sample code here that does exactly what you described: https://github.com/bitfaster/BitFaster.Caching/issues/182.

I will figure out how to do this cleanly in the next major version and have it built it. Adding it now will break the atomic/scoped features, and the time policy property for TTL should be changed to a method that resolves the TTL based on the item.
