### ISSUE TITLE
[Feature request] Allow to pass additional factory argument to the `GetOrAdd`/`GetOrAddAsync` cache methods

### ISSUE THREAD

**Issue by nahk-ivanov** [bitfaster/BitFaster.Caching#311]
Starting from .NET Framework 4.7.2 we have a [`GetOrAdd` overload](https://learn.microsoft.com/en-us/dotnet/api/system.collections.concurrent.concurrentdictionary-2.getoradd?view=netframework-4.7.2#system-collections-concurrent-concurrentdictionary-2-getoradd-1(-0-system-func((-0-0-1))-0)) for the `ConcurrentDictionary<,>` that takes in additional argument being passed to the value factory delegate. The suggestion is to add the same to the `ICache<,>.GetOrAdd` and `IAsyncCache<,>.GetOrAddAsync`.

This would eliminate the need to allocate instances for closures necessary to pass additional context/state or `CancellationToken` to the async value factories.

**Comment by bitfaster** [comment]
Thanks for the suggestion, makes total sense - I will add as part of the next release.

**Comment by bitfaster** [comment]
I have added to the underlying `ConcurrentLru` and `ConcurrentLfu` caches - this lights up the common use case. To support this in `ICache` I need to do more plumbing and will gradually chip away to get there.
