### ISSUE TITLE
[Bug] Cold queue increases infinitely for some partitions and cache sizes

### ISSUE THREAD

**Issue by rafal-mz** [bitfaster/BitFaster.Caching#365]
For some specific capacity partitions and cache sizes cold qeuue becomes unbounded an increases infinitely.

It can be observed by test `WhenKeysAreContinuouslyRequestedInTheOrderTheyAreAddedCountIsBounded` with `WarmFavourPartition` with Warm ratio `0.6` and cache sizes `64`, `128`. Its for `ConcurrentLru` implementation.

The fix is not to allow to cycle back from cold queue to warm if warm is full.

![image](https://github.com/bitfaster/BitFaster.Caching/assets/45458298/f6e9146d-d411-4c9d-8e79-ae12a9a2af7e)

**Comment by bitfaster** [comment]
Thanks for reporting this and giving a repro! I suspect your fix is correct and I made a mistake here when I changed to use Interlocked/Volatile.Read a while back. I had thought the test you mentioned would detect this, will take a look at that as well - probably the test doesn't run with both partition schemes.

**Comment by bitfaster** [comment]
Now fixed to correctly remove the coldest item after 5 attempts, constraining size within capacity.
