### ISSUE TITLE
Enumerate all cached keys

### ISSUE THREAD

**Issue by altso** [bitfaster/BitFaster.Caching#74]
It seems like this feature is not available in any of the caches.

**Comment by bitfaster** [comment]
What's your use case for enumerating keys?

I'm trying to avoid increasing the API surface unless it's really critical functionality, and usually looking inside the cache is an anti pattern.

**Comment by altso** [comment]
That was a potential workaround to clear cache. Given you can clear cache now (#73) I don't think I have a valid use case for that any longer. Thanks for looking into that.

**Comment by minhducsun2002** [comment]
I suggest reopening this issue again.

My use case is that I have an application that needs to restart regularly, and I would want to persist the cache across restarts.
